# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Hello stranger
#disqus:
#google_analytics:
#location: New York, NY
#skin: daylight
email: seyun0114kim@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/seyun" # the subpath of your site, e.g. /blog
url: ""https://mmistakes.github.io"" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  seyunkim0114

# Build settings
#theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-remote-theme
remote-theme: "mmistakes/minimal-mistakes"

author:
  name: Seyun Kim
  avatar: "profile.jpg"
  bio:
    Studying computer science, wandering everywhere
  location: New York, NY
  #email: seyun0114kim@gmail.com
  links:
    #- label: "Made Mistakes"
    #  icon: "fas fa-fw fa-link"
    #  url: "https://mademistakes.com"
    #- label: "Twitter"
    #  icon: "fab fa-fw fa-twitter-square"
    #  url: "https://twitter.com/mmistakes"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/seyunkim0114"
    #- label: "Instagram"
    #  icon: "fab fa-fw fa-instagram"
    #  url: "https://instagram.com/mmistakes"


author_profile: true
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
